---
title: Java-簡介-06
date: 2024-06-26 08:29:50
tags: 
    - 職訓
    - Java
categories: 
    - [職訓, Java]
    - Java
description: "<strong>ch.12 大型程式的發展與常用的類別庫<br></strong>
建構package的階層關係<br>
Java常用的類別庫：String、wrapper class的轉換函數、Math<br>
<strong>ch.13 例外處理</strong><br>
<strong>ch.14 檔案處理</strong><br>
認識串流<br>
學習檔案開啟與關閉<br>"
---

#### ch. 12

##### package 階層關係

##### 常用類別庫

1. 見ch.12-pg.31
2. `java.lang` 類別庫裡的所有類別會自動載入

#### ch. 13

##### 例外的基本概念

+ 撰寫程式庫的幾個常見狀況
  + 開啟的檔案不存在
  + ch.13,p.2

##### 例外處理的語法

```java
**格式**

try{

}

catch{

}

finally{

}
```

加入迴圈的例題：

```java
public class hw13_1
{
   public static void main(String args[])
   {

      double ans;
      int num=12;
         

      
      for(int i=0;i<=5;i++)
      {
         try
         {
            ans=num/i;
            System.out.println(num+"/"+i+"="+num/i);
         }
         
         catch(ArithmeticException e){
            System.out.println("除數為0");
         }
      }

      System.out.println("end of main() method !!");
   }
}  
```

{% note info %}
**Output**
除數為0
12/1=12
12/2=6
12/3=4
12/4=3
12/5=2
end of main() method !!
{% endnote %}

{% note success%}
將`try-catch`包在`for迴圈`內，
`catch`執行結束後因為還在迴圈內，所以會向下執行下一次迴圈

原本的寫法是將try-catch寫在外面包住迴圈，
這樣catch執行完後就會直接跳final，不會執行迴圈後的動作
所以很粗暴地在外面加上剩下的迴圈
但這樣邏輯不太合理，只有粗暴

每次遇到迴圈都有點死腦筋轉不過來
反應速度太慢了
{% endnote %}

##### 插播：字串比較 equals()

```java
public class hw13_3{
    public static void main(String args[]){
        String str1="Hello";
        String str2="Hello";
        String str3=new String("Hello");
        String str4=new String("Hello");

        System.out.println(str1==str2);
        System.out.println(str2==str3);
        System.out.println(str3==str4);
        System.out.println(str3.equals(str4));
    }
}
```

{% note info %}
**Output**
true
false
false
true
{% endnote %}

##### 捕捉多個例外

```java
public class hw13_2
{
   public static void main(String args[])
   {  
      int arr[]={4,12,87,21,6,18};   
      int den[]={2,0,7,0,61,0};      
      double sum=0.0;

      for(int i=0;i<=6;i++){
         try{
            sum+=arr[i]/den[i];
            System.out.println("sum="+sum);
         }
         
         catch(ArithmeticException e){
            System.out.println("除數為0");
         }
         
         catch(ArrayIndexOutOfBoundsException e){
            System.out.println("超出陣列數");
         }
      }
   }
}
```

{% note info %}
**Output**
sum=2.0
除數為0
sum=14.0
除數為0
sum=14.0
除數為0
超出陣列數
{% endnote %}

```java 範例二、Exception
public class hw13_2
{
   public static void main(String args[])
   {  
      int arr[]={4,12,87,21,6,18};   
      int den[]={2,0,7,0,61,0};      
      double sum=0.0;

      for(int i=0;i<=6;i++){
         try{
            sum+=arr[i]/den[i];
            System.out.println("sum="+sum);
         }
         
         catch(ArrayIndexOutOfBoundsException e){
            System.out.println("超出陣列數");
         }
         
         catch(Exception e){
            System.out.println("其他例外");
         }
      }
   }
}
```

{% note info %}
**Output**
sum=2.0
其他例外
sum=14.0
其他例外
sum=14.0
其他例外
超出陣列數
{% endnote %}

{% note success %}
`Exception`是`ArrayIndexOutOfBoundsException`的父類別
要放在後面執行
否則所有的例外都會被`Exception`執行，就不會跑出`ArrayIndexOutOfBoundsException`的例外
{% endnote %}

##### 拋出例外 throw

+ 於程式拋出例外
  + 系統有內定的會自動拋出

+ 指定函式拋出例外

    ```java
    函數名稱(引數) throws 例外類別1,例外類別2......{
        // 函數內程式碼
    }
    ```

例題：

```java
public class hw13_4
{
   public static void test(int num, int i) throws ArithmeticException{
   
      double ans;
      ans=num/i;
      System.out.println(num+"/"+i+"="+ans);
   
   }
   
   public static void main(String args[]){   
   
      for(int i=0;i<=5;i++){
         try{
            int num=12;
            test(num,i);
         }
         catch(ArithmeticException e){
            System.out.println("除數為0");
         }
      }
   System.out.println("end of main() method !!");
   }
}
```

{% note info %}
**Output**
除數為0
12/1=12.0
12/2=6.0
12/3=4.0
12/4=3.0
12/5=2.0
end of main() method !!
{% endnote %}

{% note success %}
注意迴圈問題
總是迴圈問題
{% endnote %}

##### 自行撰寫例外

+ 自訂例外必須繼承Expection類別

```java
class 自訂例外類別名稱 extends Exception{
    // 定義類別內的成員
}
```

來看看組合技！

```java
class NotTriangleException extends Exception{}
class RightTriangleException extends Exception{}
class NotRightTriangleException extends Exception{}

class Triangle{
   
   public void setTriangle(int a, int b, int c) throws NotTriangleException, RightTriangleException, NotRightTriangleException{
        
      if((a+b)<c || (a+c)<b || (b+c)<a){
         throw new NotTriangleException();
      }else if((a*a+b*b)==c*c){
         throw new RightTriangleException();
      }else{
         throw new NotRightTriangleException();
      }  
   }   
}

public class hw13_5{
   public static void main(String args[])
   {        
      Triangle tri=new Triangle();
         
      try{
         tri.setTriangle(3,4,5);
      }
      catch(NotTriangleException e){
         System.out.println("不構成三角形");
      }
      catch(RightTriangleException e){
         System.out.println("這是直角三角形");
      }
      catch(NotRightTriangleException e){
         System.out.println("這不是直角三角形");
      }
    }  
}
```

{% note info %}
**Output**
這是直角三角形
{% endnote %}

{% note success %}

1. 新增自訂類別並繼承
2. 自訂類別Triangle, 設定由函數拋出例外
3. 在Triangle()新增方法setTriangle(int a,int b,int c)，設定數字同時做條件判斷，符合就拋出例外（程式內拋出）
4. main()設定一個樣式是Triangle的新物件tri，執行setTriangle()
5. catch各種例外，並執行捕捉到相對例外後的程式（print相應內容）
{% endnote %}

```java 老師寫法更簡潔

class NotTriangleException extends Exception{}
class RightTriangleException extends Exception{}
class NotRightTriangleException extends Exception{}

public class hw13_5{
   public static void main(String args[])
   {  
      int a=3;
      int b=4;
      int c=5;
         
      try{
         if((a+b)<c || (a+c)<b || (b+c)<a){
            throw new NotTriangleException();
         }else if((a*a+b*b)==c*c){
            throw new RightTriangleException();
         }else{
            throw new NotRightTriangleException();
         }  
      }
      catch(NotTriangleException e){
         System.out.println("不構成三角形");
      }
      catch(RightTriangleException e){
         System.out.println("這是直角三角形");
      }
      catch(NotRightTriangleException e){
         System.out.println("這不是直角三角形");
      }
   }  
}
```

#### ch.14 檔案處理

##### 認識串流

+ 資料組成
  + 字元(characters)
  + 位元(bits)
+ 類型
  + 輸入(input stream)
  + 輸出(output stream)

##### 檔案的基本處理

+ 相關函數, 見ch.14, p.5-6
+ FileReader

    ```java
    import java.io.*;
    public class hw14_1{
        public static void main(String args[]) throws IOException{
            char data[] = new char[128];
            FileReader fr = new FileReader("C:\\java\\train.txt");
            
            int num=fr.read(data);
            String str=new String(data,0,9);
            System.out.println(str);
            
            fr.close();
        }
    }
    ```

    {% note info %}
    **Output**
    火車快飛，火車快飛
    {% endnote %}

+ FileWriter

    ```java
    import java.io.*;
    public class hw14_1{
        public static void main(String args[]) throws IOException{        
            FileWriter fw=new FileWriter("C:\\java\\proverb.txt",true);
            String str2="\r\nTime is money!";
            fw.write(str2);
            fw.close();
        }
    }
    ```

    {% note info %}
    **Output**
    Time flies!
    End of file
    Time is money!
    {% endnote %}

   {% note success %}
   先建立`train.txt`和`proverb.txt`範例檔

   要先載入函式庫`java.io.*`才能使用相關函式
   `main() throws IOException` 例外處理必須設定, 否則會報錯
   {% endnote %}
